services:
  api:
    build:
      context: .
      dockerfile: ProjectManager.Api.User/Dockerfile
    image: projectmanager-api-user
    ports:
      - "5078:80"   # Mapea el puerto 80 del contenedor al puerto 5078 del host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=server-projects-pma.database.windows.net;Database=ProjectManagerUsers;User Id=bradley;Password=2001BradFer*7;TrustServerCertificate=True;
      - JwtSettings__SecretKey=secure-key-projectmanagersecretkey123
      - JwtSettings__Issuer=ProjectManagerAPI
      - JwtSettings__Audience=*
      - Cloudinary__CloudName=ddafrj6z7
      - Cloudinary__ApiKey=986386623115898
      - Cloudinary__ApiSecret=lgXYQNlYhTTIXUesGiF_AwAEehg
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
